Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  config.vm.synced_folder ".", "/embr", automount: true

  config.vm.provider "virtualbox" do |vb|
    vb.name = "embr"
    vb.gui = false
  
    vb.memory = "2048"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt update && apt upgrade -y
    apt install make vim wget curl -y

    cp -r /embr/images /tmp

    cd /tmp

    ## Install Firecracker & Jailer
    FCVersion=1.1.1
    curl -Lo firecracker.tgz https://github.com/firecracker-microvm/firecracker/releases/download/v$FCVersion/firecracker-v$FCVersion-x86_64.tgz \
      && mkdir firecracker \
      && tar -xf firecracker.tgz -C firecracker \
      && chmod +x firecracker/release-v$FCVersion-x86_64/firecracker-v$FCVersion-x86_64 \
      && mv firecracker/release-v$FCVersion-x86_64/firecracker-v$FCVersion-x86_64 /usr/local/bin/firecracker \
      && chmod +x firecracker/release-v$FCVersion-x86_64/jailer-v$FCVersion-x86_64 \
      && mv firecracker/release-v$FCVersion-x86_64/jailer-v$FCVersion-x86_64 /usr/local/bin/jailer \
      && rm -rf /fc/firecracker*

    ## Install Go 1.19
    wget https://go.dev/dl/go1.19.linux-amd64.tar.gz && \
      tar -xvf go1.19.linux-amd64.tar.gz && \
      mv go /usr/local && \
      ln -s /usr/local/go/bin/go /usr/local/bin/go

    ## Install etcdctl
    export RELEASE=$(curl -s https://api.github.com/repos/etcd-io/etcd/releases/latest|grep tag_name | cut -d '"' -f 4) && \
      wget https://github.com/etcd-io/etcd/releases/download/${RELEASE}/etcd-${RELEASE}-linux-amd64.tar.gz && \
      tar xvf etcd-${RELEASE}-linux-amd64.tar.gz && \
      mv etcd-${RELEASE}-linux-amd64/etcd etcd-${RELEASE}-linux-amd64/etcdctl etcd-${RELEASE}-linux-amd64/etcdutl /usr/local/bin

    cd /embr; go get
  SHELL
end
