name: Go

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17.x

    - name: Checkout code
      uses: actions/checkout@v3

    - run: cd src/worker

    - name: Go Format
      run: gofmt -d -s .

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17.x

    - name: Checkout code
      uses: actions/checkout@v3

    - run: cd src/worker

    - name: Go build
      run: make worker
